{
    "custom-styles": {
    },
    "editor-colors": {
        "BackgroundColor": "#1e2832",
        "BracketMatching": "#8e44ad",
        "CodeFolding": "#224e65",
        "CurrentLine": "#28323c",
        "CurrentLineNumber": "#a5a6a8",
        "IconBorder": "#31363b",
        "IndentationLine": "#3a3f44",
        "LineNumbers": "#7a7c7d",
        "MarkBookmark": "#0404bf",
        "MarkBreakpointActive": "#8b0607",
        "MarkBreakpointDisabled": "#820683",
        "MarkBreakpointReached": "#6d6e07",
        "MarkError": "#da4453",
        "MarkExecution": "#ff007f",
        "MarkWarning": "#f67400",
        "ModifiedLines": "#c04900",
        "ReplaceHighlight": "#808021",
        "SavedLines": "#1c8042",
        "SearchHighlight": "#218058",
        "Separator": "#550000",
        "SpellChecking": "#c0392b",
        "TabMarker": "#4d4d4d",
        "TemplateBackground": "#31363b",
        "TemplateFocusedPlaceholder": "#17482d",
        "TemplatePlaceholder": "#123723",
        "TemplateReadOnlyPlaceholder": "#4d1f24",
        "TextSelection": "#2d5c76",
        "WordWrapMarker": "#32373c"
    },
    "metadata": {
        "name": "kate-theme",
        "revision": 1
    },
    "text-styles": {
        "Alert": {
            "selected-text-color": "#ffde4c",
            "text-color": "#ffde4c"
        },
        "Annotation": {
            "selected-text-color": "#aaaa1e",
            "text-color": "#aaaa1e"
        },
        "Attribute": {
            "selected-text-color": "#ff9b4d",
            "text-color": "#ff9b4d"
        },
        "BaseN": {
            "selected-text-color": "#b18500",
            "text-color": "#b18500"
        },
        "BuiltIn": {
            "selected-text-color": "#00ffff",
            "text-color": "#00ffff"
        },
        "Char": {
            "selected-text-color": "#a6c700",
            "text-color": "#a6c700"
        },
        "Comment": {
            "selected-text-color": "#00aa00",
            "text-color": "#00aa00"
        },
        "CommentVar": {
            "selected-text-color": "#aaaa78",
            "text-color": "#aaaa78"
        },
        "Constant": {
            "selected-text-color": "#0063ff",
            "text-color": "#0063ff"
        },
        "ControlFlow": {
            "selected-text-color": "#ff8c00",
            "text-color": "#ff8c00"
        },
        "DataType": {
            "selected-text-color": "#ffaa7f",
            "text-color": "#ffaa7f"
        },
        "DecVal": {
            "selected-text-color": "#b18500",
            "text-color": "#b18500"
        },
        "Documentation": {
            "selected-text-color": "#737300",
            "text-color": "#737300"
        },
        "Error": {
            "background-color": "#ff0000",
            "selected-text-color": "#ffffff",
            "text-color": "#ffffff",
            "underline": true
        },
        "Extension": {
            "selected-text-color": "#aaaaff",
            "text-color": "#aaaaff"
        },
        "Float": {
            "selected-text-color": "#b18500",
            "text-color": "#b18500"
        },
        "Function": {
            "selected-text-color": "#ff007f",
            "text-color": "#ff007f"
        },
        "Import": {
            "selected-text-color": "#55ff00",
            "text-color": "#55ff00"
        },
        "Information": {
            "selected-text-color": "#ffff7f",
            "text-color": "#ffff7f"
        },
        "Keyword": {
            "selected-text-color": "#ffff00",
            "text-color": "#ffff00"
        },
        "Normal": {
            "selected-text-color": "#ff58b1",
            "text-color": "#ff58b1"
        },
        "Operator": {
            "bold": true,
            "selected-text-color": "#ff4200",
            "text-color": "#ff4200"
        },
        "Others": {
            "selected-text-color": "#b4ff00",
            "text-color": "#b4ff00"
        },
        "Preprocessor": {
            "selected-text-color": "#00a6a6",
            "text-color": "#00a6a6"
        },
        "RegionMarker": {
            "selected-text-color": "#00ffff",
            "text-color": "#00ffff"
        },
        "SpecialChar": {
            "selected-text-color": "#ff58ff",
            "text-color": "#ff58ff"
        },
        "SpecialString": {
            "selected-text-color": "#c88c50",
            "text-color": "#c88c50"
        },
        "String": {
            "selected-text-color": "#bcbc85",
            "text-color": "#bcbc85"
        },
        "Variable": {
            "selected-text-color": "#00b1ff",
            "text-color": "#00b1ff"
        },
        "VerbatimString": {
            "selected-text-color": "#00a6ff",
            "text-color": "#00a6ff"
        },
        "Warning": {
            "selected-text-color": "#da4453",
            "text-color": "#da4453"
        }
    }
}
